#!/usr/bin/with-contenv bash

if grep -qs "$MOUNTPOINT" /proc/mounts; then
    echo "Unmounting: $MOUNTPOINT $(date +%Y.%m.%d-%T)"
    umount $UMOUNTOPTIONS $MOUNTPOINT
    wait ${!}
    exit 0
else
    echo "noting to unmount"
    exit 1
fi