#!/usr/bin/with-contenv bash

source /etc/colors.sh

PREFFIX="[cont-finish.d] $(s6-basename ${0}):"

if grep -qs "$MOUNTPOINT" /proc/mounts; then
    echo -e "${PREFFIX} ${Green}unmounting $MOUNTPOINT $(date +%Y.%m.%d-%T)${Color_Off}"
    umount $UMOUNTOPTIONS $MOUNTPOINT
    wait ${!}
    exit 0
else
    echo -e "${PREFFIX}nothing to unmount"
    exit 1
fi