#!/usr/bin/with-contenv bash

source /etc/colors.sh

PREFFIX="[cont-init.d] $(s6-basename ${0}):"

#fix Mountpoint Syntax
#remove / at the end

#create folders

#create mountpoint folder
if [ ! -d "${MOUNTPOINT}" ]; then \
mkdir -p \
	$MOUNTPOINT
fi

#check if the MOUNTPOINT is empty
if [ "$(ls -A ${MOUNTPOINT})" ]; then
    echo -e "${PREFFIX} ${Red}MountPoint folder not empty[ERROR]${Color_Off}"
    #todo
fi

#check for other fsmounts, stop mounting if other mountpoint exists
#mount | grep -c $MOUNTPOINT

if grep -qs "$MOUNTPOINT" /proc/mounts; then
    #exit container here if other mountpoint than docker volume mount is found
    #todo
    echo -e "${PREFFIX} found other mountpoint in /proc/mounts${Color_Off}"
    exit 1
else
    echo "mountpoint $MOUNTPOINT is ready"
fi