#!/usr/bin/with-contenv bash

#fix Mountpoint Syntax
#remove / at the end

#create folders

#create mountpoint folder
if [ ! -d "${MOUNTPOINT}" ]; then \
mkdir -p \
	$MOUNTPOINT
fi

#check if the mountpoint is empty


#check for other fsmounts, stop mounting if other mountpoint exists
#mount | grep -c $MOUNTPOINT

if grep -qs "$MOUNTPOINT" /proc/mounts; then
    #exit container here
    echo "found other mountpoint in /proc/mounts"
    exit 1
else
    echo "mountpoint $MOUNTPOINT is ready"
    exit 0
fi