#!/usr/bin/with-contenv sh

## Read basename
#backtick -n BASENAME { s6-basename ${0} }
#importas -u BASENAME BASENAME
#define PREFFIX "[cont-init.d] ${BASENAME}:"
define PREFFIX "[cont-init.d]:"

#ENV
OS=""
ConfigPath=""

#Functions
DetectOS(){
  if [ -e /etc/alpine-release ]; then
    OS="alpine"
  elif [ -e /etc/os-release ]; then
    if /bin/grep -q "NAME=\"Ubuntu\"" /etc/os-release ; then 
      OS="ubuntu"
    fi
  fi
}

AutoUpgrade(){
    if [ "${OS}" == "alpine" ]; then
        /sbin/apk --no-cache upgrade
        /bin/rm -rf /var/cache/apk/*
    elif [ "${OS}" == "ubuntu" ]; then
        export DEBIAN_FRONTEND=noninteractive
        /usr/bin/apt-get update
        /usr/bin/apt-get -y --no-install-recommends dist-upgrade
        /usr/bin/apt-get -y autoclean
        /usr/bin/apt-get -y clean 
        /usr/bin/apt-get -y autoremove
        /bin/rm -rf /var/lib/apt/lists/*
    fi
}

#fix Mountpoint Syntax
#remove / at the end #todo

#create folders
if [ ! -d "${MountPoint}" ]; then \
mkdir -p \
	$MountPoint \
    $ConfigDir
fi

#export config path env var in s6
#export ConfigPath="$ConfigDir/$ConfigName"
printf "$ConfigDir/$ConfigName" > /var/run/s6/container_environment/ConfigPath

s6-echo "${PREFFIX} ${C032} installing system updates${C000}"
#s6-echo "${PREFFIX} ${C133}shutdown service${C000}"
DetectOS
AutoUpgrade