#!/usr/bin/with-contenv sh

#check if the MountPoint is empty
#todo

#check for other fsmounts, stop mounting if other MountPoint exists
#mount | grep -c $MountPoint

if grep -Eq ''$RemotePath'.*'$MountPoint'|'$MountPoint'.*'$RemotePath'' /proc/mounts; then
    #exit container here
    echo "found other MountPoint in /proc/mounts"
    exit 1
else
    echo "MountPoint $MountPoint is ready"
    exit 0
fi