#!/usr/bin/with-contenv sh

#set -x

source /etc/colors.sh

PREFFIX="[services.d] [rclone-mount]-$(s6-basename ${0}):"

echo -e "${PREFFIX} ${Green}starting rclone mount $(date +%Y.%m.%d-%T)${Color_Off}"

## ECHO DEBUG
if [ "$DEBUG" = true ]; then
    echo -e "${PREFFIX} [DEBUG] command: /usr/sbin/rclone --config $ConfigPath mount $RemotePath $MountPoint $MountCommands"
if

/usr/sbin/rclone --config $ConfigPath mount $RemotePath $MountPoint $MountCommands