#!/usr/bin/with-contenv bash

if grep -qs "$MOUNTPOINT" /proc/mounts; then
    echo "force nmounting with fusermount $UnmountCommands $MountPoint at: $(date +%Y.%m.%d-%T)"
    fusermount $UnmountCommands $MountPoint
    wait ${!}
    exit 1
else
    echo "successful unmounted"
    exit 0
fi